### ISSUE TITLE
rc file? Check if PCB and schematic are new?

### ISSUE THREAD

**Issue by ghost** [JordanAceto/kicad_7_cli_doc_gen#1]
Looks nice! I have a sort of similar, but far rougher and less complete, bash script I've been using but I think I might switch over to something based on this.

Couple of possible ideas:

* ~~Could maybe read a file, call it .docgenrc or something — and maybe look for both a global one and one in the project directory — that would have parameters to modify the script behavior, for instance to turn off outputs that aren't appropriate or aren't wanted. (Schematic for a panel, for instance.) Or for instance to modify settings for Gerbers to suit different fab houses...~~ Sorry, I just saw you basically said this as a possible improvement!
* Check the modification date of the .kicad_sch file and if there's a newer existing schematic pdf skip generating a new one, likewise BOM etc.; and similarly don't regenerate gerbers, layouts, etc. if they're newer than the .kicad_pcb file. To minimize repository churn...

Question: Is there an advantage to using `os.system(f"mkdir {base_dir}")` as opposed to `os.mkdir(...)`? Or even `os.makedirs(...)` which would allow skipping over first checking for and possibly making `base_dir`? (Which could also be done using `os.system(f"mkdir -p {base_dir}/file")`, I guess...)

**Comment by JordanAceto** [comment]
Hello Rich! Nice to hear from you, I actually used some ideas from your ribbon controller when I was recently poking around with one of my own 🙂

I like your date-checker idea. Repo churn does get pretty yucky with so many outputs.

Re your question about `mkdir` and why I did it that way: haha, the answer is that when making this script I was basically going through the help menu of `kicad-cli` in the terminal to see what outputs were available, manually playing around with commands to get the output I wanted, and then quickly adding it to the script in the form of an `f-string` without thinking too much. Did I mention quick and dirty?

The way the directory structure is made could definitely be improved in the way you described. It is not so graceful currently when you overwrite old docs. The CSV BOM is similarly hacky atm. I must emphasize that the current script is really just a snapshot in time so I don’t forget where I was at.

I probably won’t make any changes riiiiiight way, but I would like to incorporate the things you’ve described eventually. I would welcome pull requests, or if you go in your own direction I’d love to peek at what you come up with 🙂

**Comment by ghost** [comment]
OK, I have a first stab at a new version here:

https://github.com/holmesrichards/kicad_7_cli_doc_gen/tree/rsh

Broadly the changes are:

* Behavior is controlled by parameters read from configuration files.
* *All* kicad projects below the specified directory are processed, not just the first one found. (e.g. if there is one project for a PCB and one for a front panel.)
* No file is regenerated if it would overwrite an existing file that is newer than the KiCad file it is generated from. (This is a little foggy when it comes to Gerbers. Do you skip generating them if *any* existing file is newer than the PCB, or only if *all* of them are? I can see arguments either way. I implemented the second.)

I like using KiKit for generating Gerbers, so I put in a placeholder for that option, but I haven't implemented it yet. I think the Ubuntu KiCad 7.0 package is incompatible with KiKit, probably to be fixed in 7.0.1.

Also I removed all the 7s in the script because they'd just have to be changed to 8s in a year anyway. I left the 7 in the script name though.

This has *not* been thoroughly tested! Probably lots of bugs.

**Comment by JordanAceto** [comment]
Wow, this is great, and so fast!

When I get a minute I'll fire up your changes and try it with a few projects.

I agree with the choice to get rid of as many `7`s as possible, the yearly release cycle does go fast!

Re when to regenerate the gerbers: I personally don't care too much, as long as the gerbers match reality.

**Comment by ghost** [comment]
At this point there may be more new code than old, though the old is mostly still in there. It's changed a lot though the default behavior on a directory containing a single project is still nearly the same. Pretty happy with my version.

https://github.com/holmesrichards/kdocgen

**Comment by JordanAceto** [comment]
I had actually cloned your new repo earlier this morning and have been playing with it, trying out multi-board projects with a mix of 2 and 4 layer boards, etc. This is all fantastic., you did most of what I had hoped to eventually get to.

At this point I’m not sure what to do with this original script. I think for the time being I’ll just keep my existing script as a “bare bones starting point” and update the README to point to your updated version for people wanting a polished solution. I may revisit this at some point, but I'll probably just use your version for now.

Thanks and nice work!
